### ISSUE TITLE
Placeholder not working

### ISSUE THREAD

**Issue by chicoferreira** [INB-It-s-not-a-bukkit/INB#26]
**Describe the bug**
Placeholders are not working as expected in gamemode command.

**To Reproduce**
1. Type `/gamemode <non_existing_gamemode>`

**Expected behavior**
Should show the argument that the user typed.

**Screenshots**
![image](https://user-images.githubusercontent.com/36338391/78594751-bf3e6980-7840-11ea-8bb1-6b603eafb28a.png)

**Comment by TommyAlmeida** [comment]
fixed
