### ISSUE TITLE
Gamemode command not working

### ISSUE THREAD

**Issue by chicoferreira** [INB-It-s-not-a-bukkit/INB#40]
**Describe the bug**
When someone tries to change gamemode with /gamemode he gets kicked with an ``DecoderException`` error.

**To Reproduce**
1. Open chat with ``T`` (default key)
2. Type ``/gamemode something``

**Expected behavior**
The players should have their gamemode changed to the input gamemode.

**Screenshots**
![image](https://user-images.githubusercontent.com/36338391/79083713-d80abb80-7d27-11ea-907e-4bdf15409880.png)

**Comment by TommyAlmeida** [comment]
The reason for this to happening is because the playEffect packet is sending x, y, z instead of sending the position packed into a long with bitshifted values from x, y, z. Already fixing.
